# Gopkg.toml example
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/telemetry/thing/cmd/thing"]
# ignored = ["github.com/telemetry/project/pkgX", "bitbucket.org/telemetry/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/telemetry/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/telemetry/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[prune]
  go-tests = true
  unused-packages = true
  [[prune.project]]
        name = "github.com/aws/aws-sdk-go"
        non-go = false
        unused-packages = false


[[constraint]]
  name = "go.uber.org/zap"
  version = "1.10.0"

[[constraint]]
  name = "github.com/go-pg/pg"
  version = "6.15.1"

[[constraint]]
  name = "gopkg.in/robfig/cron.v3"
  version = "3.0.0-rc1"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.2"
[[constraint]]
  name = "github.com/nats-io/stan"
  version = "0.5.0"
[[constraint]]
  name = "github.com/google/wire"
  version = "0.3.0"

[[constraint]]
  name = "github.com/tsuyoshiwada/go-gitlog"
  version = "1.0.0"

[[constraint]]
  name = "gopkg.in/src-d/go-git.v4"
  version = "4.13.1"

[[constraint]]
  name = "github.com/optiopay/klar"
  version = "2.4.0"

[[constraint]]
  name = "gopkg.in/go-playground/validator.v9"
  version = "9.28.0"

[[constraint]]
  branch = "master"
  name = "github.com/juju/errors"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.16.34"
[[constraint]]
  name = "github.com/jasonlvhit/gocron"
  version = "0.1.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "1.5.2"
