// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/devtron-labs/external-app-crawler/api"
	"github.com/devtron-labs/external-app-crawler/client"
	"github.com/devtron-labs/external-app-crawler/internal/logger"
	"github.com/devtron-labs/external-app-crawler/internal/sql"
	"github.com/devtron-labs/external-app-crawler/pubsub"
)

// Injectors from Wire.go:

func InitializeApp() (*App, error) {
	sugaredLogger := logger.NewSugardLogger()
	restHandlerImpl := api.NewRestHandlerImpl(sugaredLogger)
	muxRouter := api.NewMuxRouter(sugaredLogger, restHandlerImpl)
	config, err := sql.GetConfig()
	if err != nil {
		return nil, err
	}
	db, err := sql.NewDbConnection(config, sugaredLogger)
	if err != nil {
		return nil, err
	}
	pubSubClient, err := client.NewPubSubClient(sugaredLogger)
	if err != nil {
		return nil, err
	}
	natSubscriptionImpl, err := pubsub.NewNatSubscription(pubSubClient, sugaredLogger)
	if err != nil {
		return nil, err
	}
	app := NewApp(muxRouter, sugaredLogger, db, natSubscriptionImpl)
	return app, nil
}
